export * from "./bank-filter.dto";
export * from "./bank-image.dto";
export * from "./bank-list-item.dto";
export * from "./bank.detail.dto";
export * from "./bank.dto";
export * from "./create-bank.dto";
export * from "./create-media-bank.dto";
export * from "./update-bank.dto";
export * from "./bank-list.dto"